spring:
  datasource:
    url: jdbc:mysql://localhost:3306/propertymanagement?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
  mvc:
    datefor


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.sjzc.propertymanagment.pojo